### ISSUE TITLE
Normal usage state without "Connector"

### ISSUE THREAD

**Issue by 0xF6** [BerserkerDotNet/BlazorState#1]
possible?

**Comment by BerserkerDotNet** [comment]
The short answer, it depends :)

The long answer:
If we're talking about components, then no, it is not recommended and not supported.
You should use "Connector" to connect your component to the store.
Connecting components to the store is idiomatic to React-Redux and I've tried to have the same pattern for Blazor-Redux. 

If we're talking about some other parts of the application, you can certainly inject the `IStore` interface directly and subscribe to state change and read the state directly,

Can you elaborate more on the scenario that you have where "Connector" does not fit?

**Comment by 0xF6** [comment]
I was looking for a state manager implementation that supports redux-dev-tools and doesn't force me to write a lot of code.
And using connector's I have to write a lot of code, as well as violate the architectural approach to development on blazor.

Thanks for reply for my question, I chose [blazor-state](https://github.com/TimeWarpEngineering/blazor-state) and until that me this option suits :)

**Comment by BerserkerDotNet** [comment]
@0xF6, sure, I'll close the issue. Just out of curiosity, what architectural approach you're referring to?
