### ISSUE TITLE
ReduxDevTools not installed

### ISSUE THREAD

**Issue by KevinBurton** [BerserkerDotNet/BlazorState#10]
I look on the Chrome debugger console and I see the message:
![image](https://user-images.githubusercontent.com/2643566/111080940-e54b9f80-84ce-11eb-9218-fe61b6047a6c.png)
I have the dev tools installed
![image](https://user-images.githubusercontent.com/2643566/111080971-1035f380-84cf-11eb-8888-32142a336504.png)
Here is some more detail
![image](https://user-images.githubusercontent.com/2643566/111081092-905c5900-84cf-11eb-90e3-a0b1c1ecb519.png)

**Comment by BerserkerDotNet** [comment]
@KevinBurton, I can't seems to repro this with exactly the same version of dev tools. It works correctly in both Chrome and in Edge.
Can you check if there is Redux tab in the dev tools?
![image](https://user-images.githubusercontent.com/1640125/118384348-41f43500-b5ba-11eb-8aec-601841ca3f1a.png)

Also, Chrome disables extensions for incognito window and I noticed that when you start a debugger, the browser instance does not have the same set of extensions as the non-debug window :/
