### ISSUE TITLE
Render component and Props

### ISSUE THREAD

**Issue by KevinBurton** [BerserkerDotNet/BlazorState#12]
I have a significant amount of code on the page (I will call it Grouping.razor). I would like to connect it to the state. Reading the documentation I see that is done by a call to the static 'Get' that returns a RenderFragment. But the samples show the RenderFragment on the page. This seems like a Catch-22. Say my page looks like:

`<p> This is a test </p>`

and I have code behind that includes the Props like

```
        [Parameter]
        public GroupingProps Props { get; set; }

```
From the documentation I see lines like

```
@page "/counter"

@CounterCmp

@code {
    RenderFragment CounterCmp = CounterConnected.Get();
}

```

So if I was to extend this to my page I would do something like

```
<p> This is a test </p>
@GroupingCmp 
@code {
    RenderFragment GroupingCmp = GroupingConnect.Get();
}

```

I have tried calling 'Get' in OnInitializedAsync and just ignoring the return RenderFragment but the Props parameter is always null. How do I connect the page to the state?

**Comment by BerserkerDotNet** [comment]
There was no way to do it in v1.0. I've added such possibility to v1.1.1, checkout [CounterPageConnected](https://github.com/BerserkerDotNet/BlazorState/blob/master/samples/BlazorState.Sample/Pages/CounterPageConnected.razor)
