### ISSUE TITLE
Async actions exemple

### ISSUE THREAD

**Issue by PollegGames** [BerserkerDotNet/BlazorState#14]
Hi,

I'm really enjoing your work but i would implement something like 'DeleteIdentity IAsyncAction' but there are no sample code for this.

May you give me some info, source code, link or anithing that can let me understand better this concept please?

Thanks

Best regards

**Comment by BerserkerDotNet** [comment]
Hi @DrTekno, thanks for the kind words :)

My bad for not including IAsyncAction implementation sample, I'll fix that.

To create an async action, write a class that implements `IAsyncAction` interface. Declare services that you want to use in the constructor. These services will be injected into the action via dependency injection framework. Implement `Execute` method.

Here is one example of how to implement IAsyncAction that I use in my other application (not on GitHub yet)
```csharp
    public class FetchExercisesAction : IAsyncAction
    {
        private readonly IExerciseLogRepository _repository;
        private readonly ICacheService _cacheService;

        public FetchExercisesAction(IExerciseLogRepository repository, ICacheService cacheService)
        {
            _repository = repository;
            _cacheService = cacheService;
        }

        public async Task Execute(IDispatcher dispatcher)
        {
            if (_cacheService.IsExercisesCached())
            {
                var exercises = await _cacheService.GetExercises();
                dispatcher.Dispatch(new ReceiveExercisesAction(exercises));
            }
            else
            {
                var exercises = await _repository.GetAll<Exercise>();
                await _cacheService.SaveExercises(exercises);
                dispatcher.Dispatch(new ReceiveExercisesAction(exercises));
            }
        }
    }
```
Make sure to register your actions with dependency injection container by adding `cfg.RegisterActionsFromAssemblyContaining<FetchExercisesAction>();`. This will register all async actions from the assembly. 

Once that is done, the action can be dispatched in the connected component like by calling `await store.Dispatch<FetchExercisesAction>();`

More info can be found [here](https://github.com/BerserkerDotNet/BlazorState#async-actions) as well.

Hope this helps :)

**Comment by PollegGames** [comment]
Hello @BerserkerDotNet ,

Thank you for replying so quickly! And yes this help me but I have 1 more question:

From the 'razor.cs' componenets how you call the `await store.Dispatch<FetchExercisesAction>();` ? 

I think is on the 'Init' method but may you show me an exemple of it please? Like if we have multiple IAsyncAction how you manage to handle it properly in the connected component and also call it from the razor page from a button i.e?

Thanks

Best regards



**** edit after some test **** 

I've try to find a solution my self and i want to show it here, hoping i've done it right that maybe help other devs.

I'm using AntDesign for render the table and 1621 users in my json file.

So basically i have my razor component 

```
 @if (Props != null && Props.Utilisateurs != null)
            {
            <Table DataSource=@Props.Utilisateurs Total=@Props.TotalPage PageIndex=@Props.PaginationProps.PageIndex
            PageSize=@Props.PaginationProps.PageSize OnPageIndexChange="PageIndexChanged"
            OnPageSizeChange="PageSizeChanged">

                <AntDesign.Column DataIndex="Prenom" TData="string">
                    <Text>@context.Prenom @context.Nom</Text>
                </AntDesign.Column>

            </Table>

            }

```

with some @code in it

```
 [Parameter] public UtilisateurProps Props { get; set; }
    private void PageIndexChanged(PaginationEventArgs args)
    {
        Props.PaginationProps.PageIndex = args.Page;
        Props.GetUtilisateur.InvokeAsync(Props.PaginationProps);

    }
    private void PageSizeChanged(PaginationEventArgs args)
    {
        Props.PaginationProps.PageSize = args.PageSize;
        Props.GetUtilisateur.InvokeAsync(Props.PaginationProps);
    }
```
then i have my razor.cs component

 ```
protected async override Task Init(IStore<RootState> store)
        {
            //await store.Initialize(); //this line retrieve last data ? todo how this is working ? 
            if (store == null || store.State == null)
            {
                await store.Dispatch<FetchUtilisateur>();
            }
        }

        protected override void MapStateToProps(RootState state, UtilisateurProps props)
        {
            //props.PaginationProps = new PaginationFilter(10,10);
            if (state != null && state.Utilisateur != null)
            {
                props.Utilisateurs = state.Utilisateur.Utilisateurs;
                props.TotalPage = state.Utilisateur.TotalPage;
                props.PaginationProps = state.Utilisateur.PaginationProps;
            }
        }

        protected override void MapDispatchToProps(IStore<RootState> store, UtilisateurProps props)
        {   
            props.GetUtilisateur = EventCallback.Factory.Create(this, () =>
           {
               store.Dispatch<GetUtilisateur, PaginationFilter>(props.PaginationProps);
           });

        }
```
and is calling my IAsyncAction here

 ```
 public class GetUtilisateur : IAsyncAction<PaginationFilter>
    {
        public List<UtilisateurType> Utilisateurs { get; set; }

        private readonly HttpClient _http;

        public GetUtilisateur(HttpClient http)
        {
            _http = http;
        }

        public async Task Execute(IDispatcher dispatcher, PaginationFilter paginationProps)
        {
            UtilisateurType[] utilisateurs = await _http.GetFromJsonAsync<UtilisateurType[]>("sample-data/utilisateur.json");
           
            var pagedData = utilisateurs
               .Skip((paginationProps.PageIndex - 1) * paginationProps.PageSize)
               .Take(paginationProps.PageSize)
               .ToList();

            dispatcher.Dispatch(new ReceiveUtilisateurAction
            {
                Utilisateurs = pagedData,
                TotalPage = utilisateurs.Length,
                PaginationProps = paginationProps
            });

        }
    }
```

and giving back the result to my Reducer here

```
 public UtilisateurState Reduce(UtilisateurState state, IAction action)
        {
            switch (action)
            {
                case InitUtilisateurAction a:
                    return new UtilisateurState(a.Utilisateurs, a.TotalPage, a.PaginationProps);

                case ReceiveUtilisateurAction a:
                    return new UtilisateurState(a.Utilisateurs, a.TotalPage, a.PaginationProps);

                default:
                    return state;
            }
        }
```
Finally this is working just fine for an application with the purpose to test your library, but I'am wondering if I'am missing something or if there a way to do it better and more proper.

For exemple you have write to use `await store.Dispatch<FetchExercisesAction>();` but it seems not necessary the using of 'await' IMO.

**Comment by BerserkerDotNet** [comment]
Hi @DrTekno, your code looks correct to me. AsyncAction can be triggered in two ways, one is from `Init` method, this is for cases when you need to get some initial data to render your component. Another place is from the callback in the props. These callbacks are mapped in the `MapDispatchToProps` method. These callbacks can be used on event handlers like button click.
One thing I want to point out in you example is the lack of `async/await` in the `PageSizeChanged` and `PageIndexChanged`, I'm not familiar with the `AntDesign` components , but if there are async versions of these events, I'd recommend to use them.
The reason is to avoid having some code after the event handler run before the event handler actually finishes :)

As to your question about `Like if we have multiple IAsyncAction how you manage to handle it properly in the connected component`. If those are separate actions that will be invoked from different buttons on the components, then you map them separately in the `MapDispatchToProps`.
