### ISSUE TITLE
Setting up a component to use state

### ISSUE THREAD

**Issue by KevinBurton** [BerserkerDotNet/BlazorState#9]
I have a component that I have set up but I am getting a null reference exception and I am trying to see what I am doing wrong.
Here is what I am using
```
    public partial class ProjectPicker
    {
        public static RenderFragment Get()
        {
            var c = new ProjectPicker();
            return ComponentConnector.Connect<ProjectPicker, BreakpointManagementState, ProjectProps>(c.MapStateToProps, c.MapDispatchToProps);
        }

        private void MapStateToProps(BreakpointManagementState state, ProjectProps props)
        {
            props.Project = state?.Project ?? new BreakpointProjectSummary();
        }

        private void MapDispatchToProps(IStore<BreakpointManagementState> store, ProjectProps props)
        {
            props.UpdateProject = EventCallback.Factory.Create(this, () =>
            {
                store.Dispatch(new UpdateProjectAction());
            });
        }
```
The first thing I see that is wrong is that the example shown in the README shows a class not partial as I have shown. My class is the code behind for ProjectPicker.razor component. 
Second, the first type parameter for Connect is wrong because it cannot be converted to ComponentBase. What are the types to be used for the Connect<T,U,V> method?
![image](https://user-images.githubusercontent.com/2643566/111017822-32b6f800-837b-11eb-93f5-881723eebaca.png)

**Comment by KevinBurton** [comment]
I think I have it now. The issue I am running into is that the [Parameter] Props is always null? Here is my configuration
```
            services.AddReduxStore<BreakpointManagementState>(cfg =>
            {
                cfg.UseReduxDevTools();
                // Register Async actions
                cfg.Map<DrugReducer, Drug>(s => s.Drug);
                cfg.Map<OrganismReducer, OrganismName>(s => s.Organism);
                cfg.Map<ProjectReducer, BreakpointProjectSummary>(s => s.Project);
                cfg.Map<StandardReducer, BreakpointStandard>(s => s.Standard);
                cfg.Map<SummaryReducer, BreakpointSummary>(s => s.Summary);
                // Store current page location in state
                cfg.TrackUserNavigation(s => s.Location);
            });

```
I noticed that one difference with the sample is that I am using Client side hosting. Is that an issue?

**Comment by BerserkerDotNet** [comment]
@KevinBurton, I think the issue is because `ProjectPicker` is the component you are trying to connect. Try making this class separate from `ProjectPicker`, for instance `ProjectPickerConnected`.

**Comment by BerserkerDotNet** [comment]
I've changed the way how Connected component is defined in v1.1.1, please take a look at [Counter sample](https://github.com/BerserkerDotNet/BlazorState/blob/master/samples/BlazorState.Sample/Components/Counter.razor.cs).
